// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type AuthProvider struct {
	Provider  string     `json:"provider"`
	UserID    uint64     `json:"user_id"`
	UID       string     `json:"uid"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

type Mutation struct {
}

type NewAuthProvider struct {
	Provider string `json:"provider"`
	UserID   uint64 `json:"user_id"`
	UID      string `json:"uid"`
}

type NewPost struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	UserID      uint64 `json:"user_id"`
}

type NewRegisterUser struct {
	FirstName      string `json:"first_name"`
	LastName       string `json:"last_name"`
	Email          string `json:"email"`
	IsConfirmed    *bool  `json:"is_confirmed,omitempty"`
	AcceptedTos    bool   `json:"accepted_tos"`
	Password       string `json:"password"`
	RepeatPassword string `json:"repeat_password"`
}

type NewToken struct {
	UserID      uint64    `json:"user_id"`
	Token       string    `json:"token"`
	TokenTypeID uint64    `json:"token_type_id"`
	Code        *string   `json:"code,omitempty"`
	ExpiresAt   time.Time `json:"expires_at"`
}

type NewUser struct {
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	Email       string `json:"email"`
	IsConfirmed *bool  `json:"is_confirmed,omitempty"`
	AcceptedTos bool   `json:"accepted_tos"`
}

type Post struct {
	ID          uint64     `json:"id"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	UserID      uint64     `json:"user_id"`
	User        *User      `json:"user"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	UpdatedAt   *time.Time `json:"updated_at,omitempty"`
	DeletedAt   *time.Time `json:"deleted_at,omitempty"`
}

type Query struct {
}

type Token struct {
	ID          uint64     `json:"id"`
	UserID      uint64     `json:"user_id"`
	Token       string     `json:"token"`
	TokenTypeID uint64     `json:"token_type_id"`
	Code        *string    `json:"code,omitempty"`
	ExpiresAt   time.Time  `json:"expires_at"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	UpdatedAt   *time.Time `json:"updated_at,omitempty"`
}

type User struct {
	ID          uint64     `json:"id"`
	FirstName   string     `json:"first_name"`
	LastName    string     `json:"last_name"`
	Email       string     `json:"email"`
	IsConfirmed *bool      `json:"is_confirmed,omitempty"`
	AcceptedTos *bool      `json:"accepted_tos,omitempty"`
	Posts       []*Post    `json:"posts"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	UpdatedAt   *time.Time `json:"updated_at,omitempty"`
	DeletedAt   *time.Time `json:"deleted_at,omitempty"`
}
