// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type Mutation struct {
}

type NewAuthProvider struct {
	Provider string `json:"provider"`
	UserID   uint64 `json:"user_id"`
	UID      string `json:"uid"`
}

type NewPost struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	UserID      uint64 `json:"user_id"`
}

type NewRegisterUser struct {
	FirstName      string `json:"first_name"`
	LastName       string `json:"last_name"`
	Email          string `json:"email"`
	Password       string `json:"password"`
	RepeatPassword string `json:"repeat_password"`
}

type NewToken struct {
	UserID      uint64    `json:"user_id"`
	Token       string    `json:"token"`
	TokenTypeID uint64    `json:"token_type_id"`
	Code        *string   `json:"code,omitempty"`
	ExpiresAt   time.Time `json:"expires_at"`
}

type NewUser struct {
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	Email       string `json:"email"`
	IsConfirmed *bool  `json:"is_confirmed,omitempty"`
	AcceptedTos bool   `json:"accepted_tos"`
}

type Query struct {
}
